### PR TITLE
Feature/use custom job class

### PR DESCRIPTION
**Pull request by adm-bome**
An different way for people who have issues working with messages not created by the laravel QueueAPI
refference issues: #338, #368

and my vision on PR #353 without factory

### CODE REVIEW

**Comment by gpibarra** [comment]
any news?

**Comment by adm-bome** [comment]
> any news?

Not yet...
@vyuldashev  has to shine it's lights onto this code and may or may not review this ;)

**Comment by vyuldashev** [comment]
I like the implementation. Started review yesterday. The plan is to release it along with support for PHP 8.0

**Comment by vyuldashev** [comment]
v11.1.0 released. Thanks!

**Pull request merged**
