### PR TITLE
Laravel 7.0 Compatibility

### PR DESCRIPTION
**Pull request by tsonevpetyo**
Everything should work. No breaking changes on the Queue API

### CODE REVIEW

**Comment by Megachill** [comment]
This should be re-opened or at least considered to be merged in. Current latest repo not working w Laravel 7.x as you won't have `"illuminate/queue": "^6.0",` which needs to change as per this request to be compatible with Laravel 7.x as `illuminate/queue": "^7.0"` is now required.

#329

**Comment by sergiy-petrov** [comment]
@tsonevpetyo wondering why did you close it?

**Comment by tsonevpetyo** [comment]
> @tsonevpetyo wondering why did you close it?
As far as I remember there was already such PR with the same changes... I can open it again if u want.

**Comment by sergiy-petrov** [comment]
@tsonevpetyo sorry missed that

**Pull request closed without merging**
