### PR TITLE
Feature/use custom job class v10

### PR DESCRIPTION
**Pull request by adm-bome**
An different way for people who have issues working with messages not created by the laravel QueueAPI
refference issues: #338, #368

and my vision on PR #353 without factory

### CODE REVIEW

**Review by adm-bome — COMMENTED** [review]
@vyuldashev, we can close the PR for the master. If you can cherrypick or merge V10 branch into the master branch?

**Comment by vyuldashev** [comment]
@adm-bome According to our support policy we add new features only to the latest version.

**Comment by adm-bome** [comment]
Yep, i know.

This feature was introduced at the same time branch version 11 was released.

Version 11 was created only for  the new horizon and is not backwardcompattible, because of that.

That meens versions of laravel 6 and 7 with an old structure can't use this feature.

As i see it... when the feature is also in version 10 more people can use this. (Including myself) 

The changes don't interfer with support for horizon 3 as of version 11.

**Comment by adm-bome** [comment]
Ps: by eccident i restored the branch. 

Maybe you can reconsider your choice of not implementing this feature into v10. 
Its not a major change for how the library is working.

But i will respect your choice when you think its not worth it and please delete the branch

**Pull request closed without merging**
