### PR TITLE
queue: accept custom RabbitMQQueue class

### PR DESCRIPTION
**Pull request by hex7c0**
Add the ability to change Queue class

queue.php configuration file can be
`'worker' => \App\Providers\Foo::class,`

and Foo class should be something like

```php
/**
 * Class Foo.
 */
class Foo extends RabbitMQQueue
{
}
```

### CODE REVIEW

**Comment by hex7c0** [comment]
hey @vyuldashev, any news?

**Comment by vyuldashev** [comment]
Released this feature v8.3.0. Class should be instance of `RabbitMQQueue`

**Comment by hex7c0** [comment]
man I'm sorry, how is possible that your code work if I put this in the configuration file?

'worker' => \App\Providers\Foo::class,

**Comment by vyuldashev** [comment]
@hex7c0 You call should be instance of RabbitMQQueue class from this package.

**Comment by hex7c0** [comment]
yes but in the configuration queue.php file I just set my class

*if* I have to instance the class, I have to pass `AmqpContext $context, array $config` repeating your code and I think that is unnecessary duplication

what do you think?

**Comment by anolek** [comment]
Agree with @hex7c0 

Instead of using "instanceof", we could use "is_subclass_of()" and this will work fine (for string classname and instance of RabbitMQQueue)

**Comment by hex7c0** [comment]
gentle ping

**Pull request closed without merging**
