### PR TITLE
Amqp interop based version.

### PR DESCRIPTION
**Pull request by makasim**
ref https://github.com/vyuldashev/laravel-queue-rabbitmq/issues/153

This is far from the final version, the aim of this PR is to show differences in approaches.

### CODE REVIEW

**Comment by vyuldashev** [comment]
I like the approach, I guess we can use it in v6.0. Does enqueue support SSL connections?

**Comment by makasim** [comment]
> Does enqueue support SSL connections?

Not yet, I am going to work on it before continue with this PR

**Comment by makasim** [comment]
now Enqueue supports secure connections: https://github.com/php-enqueue/enqueue-dev/pull/246

**Comment by vyuldashev** [comment]
Nice, so I wait for your pull request to be complete.

**Comment by makasim** [comment]
The code was tested manually in a sandbox app. More or less working. 

Can I use phpunit built-in mocker in the tests?

**Comment by vyuldashev** [comment]
@makasim It's better to use real rabbitmq instance in tests.

**Comment by makasim** [comment]
> @makasim It's better to use real rabbitmq instance in tests.

I don't understand. Would you like to have functional tests that interact with a real RabbitMQ broker?

**Comment by vyuldashev** [comment]
@makasim It would be awesome.

**Comment by makasim** [comment]
I am fine with writing them though I don't think it worth it. Enqueue transports have a lot of functional tests.

**Comment by makasim** [comment]
@vyuldashev ready for review. There is one failing test (ssl connection). I am going to fix it tomorrow beside that everything else is ready.

**Comment by makasim** [comment]
@vyuldashev All is green and ready for review

**Comment by makasim** [comment]
@vyuldashev When will you have time to review?

**Comment by vyuldashev** [comment]
@makasim Is it already ready? I see tests are failing. Did you test this version on a Laravel app?

**Comment by makasim** [comment]
@vyuldashev yes it is ready, tests failed because of the latest fix. I'll fix them asap. 

I tested several flows here https://github.com/php-enqueue/enqueue-sandbox/pull/9

**Comment by makasim** [comment]
I'll be able to provide support in case of issues after merging it. I'll keep an eye on issues and comment or you can ping me

**Comment by vyuldashev** [comment]
@makasim I merged your PR, thanks. But before releasing I want to make some changes.

**Comment by vyuldashev** [comment]
@makasim This version is available as `dev-master / 6.0.x-dev` for now.

**Comment by vrubiella** [comment]
@makasim I'm sorry for breaking the tests, I see you fixed now. :+1:

**Comment by makasim** [comment]
@vrubiella np

**Comment by makasim** [comment]
@vyuldashev is there any ETA for rolling 6.0 release? thank you.

**Comment by vyuldashev** [comment]
@makasim Next week I will have a look and make a release.

**Comment by makasim** [comment]
@vyuldashev are there any news on the release? thanks

**Comment by vyuldashev** [comment]
@makasim sorry was very busy. Let’s release it tonight. Did you test 6.0-dev? Does it work as expected with new configuration and amqp-interop?

**Comment by makasim** [comment]
works for us.

**Comment by vyuldashev** [comment]
Released.

**Pull request merged**
