### PR TITLE
Fixing attempts incrementing:

### PR DESCRIPTION
**Pull request by mrvtoney**
In the RabbitMQQueue.php:
- $message was changed to a class property ($this->message)

In the RabbitMQJob.php:
- class const ATTEMPT_COUNT_HEADERS_KEY was changed from “attempts_count” to “attempts”

### CODE REVIEW

**Comment by mrvtoney** [comment]
@vyuldashev I can't figure out what errored out for the styleci/pr check. Can you point it out for me?

**Comment by vyuldashev** [comment]
> $message was changed to a class property ($this->message)
I don't think it's a good idea. Why did you add this?

**Comment by mrvtoney** [comment]
The message was a class property in the RabbitMQJob as well.

However, simply changing the value of the const ATTEMPT_COUNT_HEADERS_KEY did not fix the problem as a whole.

The message's state needed to persist through the process in order to increment. Every time the message was used it was recreated but when it was recreated. It did not take into consideration or apply the logic for the attempts. Meaning that each time a new message was created and the attempts were set to one again instead of incrementing(if at all).

**Comment by vyuldashev** [comment]
I just [pushed](https://github.com/vyuldashev/laravel-queue-rabbitmq/commit/d7dafddbbd303c75ac63e6b016cc0dd369f27f96) tests for job attempts. And seems like it works like expected: https://travis-ci.org/vyuldashev/laravel-queue-rabbitmq/jobs/613081677

Also, we are using this library in many application in production which somehow have logic with attempts count and everything works.

**Comment by mrvtoney** [comment]
That is great to hear.

Yeah. While going through the laravel worker code. I saw that database, redis and sync all utilized attempts.

I modified it in order to maintain consistency with laravel's other queue drivers.

I can change it back and test on my side to see if the change from attempt_counts to attempts.

**Comment by mrvtoney** [comment]
@vyuldashev I tested and changed 'attempts' back to 'attempts_count'

**Comment by vyuldashev** [comment]
So why do I need to accept this PR if attempts are incrementing?

**Comment by mrvtoney** [comment]
Attempts do not increment without the changes to RabbitMQQueue.php.

The attempt_count isnt incrementing. It fixes this issue:

https://github.com/vyuldashev/laravel-queue-rabbitmq/issues/235

**Comment by mrvtoney** [comment]
@vyuldashev do you have any other suggestions for my PR?

**Comment by vyuldashev** [comment]
I will review and test it and probably this goes to v10

**Comment by vyuldashev** [comment]
I tried your code, seems like it does not fix #235

**Comment by mrvtoney** [comment]
@vyuldashev Can you send me the steps you used to test so I can test again on my side, please?

**Comment by vyuldashev** [comment]
@mrvtoney I used the same code from #235 
I think I found a solution but it will break BC. So, I need to work on it and it will go to v10

**Pull request closed without merging**
