### PR TITLE
Support Laravel 7

### PR DESCRIPTION
**Pull request by serderovsh**

### CODE REVIEW

**Comment by snezhkoigor** [comment]
Когда сольется?

**Comment by bandgeekndb** [comment]
@vyuldashev Any chance you'll be able to review this soon? Looking to update our applications to Laravel 7 once this is updated. Thank you!

**Comment by Megachill** [comment]
@vyuldashev same for us, we are using forks right now to make our apps work, be nice if this could get approved.

**Comment by idsulik** [comment]
@vyuldashev , can U pls accept the mr?

**Comment by smskin** [comment]
We are waiting for the approve request

**Comment by vyuldashev** [comment]
Use master branch for now, please. I do not have much time to make a release atm.

**Pull request merged**
