### PR TITLE
PHP 8 Support

### PR DESCRIPTION
**Pull request by voyula**
PHP 8 is officially released.
@vyuldashev

### CODE REVIEW

**Comment by voyula** [comment]
@adm-bome

**Comment by vyuldashev** [comment]
We need configuration for Travis too. And if you run `composer update` with 8.0 you will see that: 
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - friendsofphp/php-cs-fixer[dev-master, v2.16.0, ..., 2.16.x-dev] require php ^5.6 || ^7.0 -> your php version (8.0.0) does not satisfy that requirement.
    - friendsofphp/php-cs-fixer v2.16.6 requires php ^7.0 -> your php version (8.0.0) does not satisfy that requirement.
    - friendsofphp/php-cs-fixer v2.16.7 requires php ^7.1 -> your php version (8.0.0) does not satisfy that requirement.
    - friendsofphp/php-cs-fixer 2.17.x-dev is an alias of friendsofphp/php-cs-fixer dev-master and thus requires it to be installed too.
    - Root composer.json requires friendsofphp/php-cs-fixer ^2.16 -> satisfiable by friendsofphp/php-cs-fixer[v2.16.0, ..., 2.17.x-dev (alias of dev-master)].
```

**Comment by vyuldashev** [comment]
Sorry, but php-amqplib does not support PHP 8 at the moment: https://github.com/php-amqplib/php-amqplib/issues/846. I have to revert changes.

**Comment by voyula** [comment]
@vyuldashev 👍

**Pull request merged**
