### PR TITLE
Add a new option connection_method_socket for gaining better performance

### PR DESCRIPTION
**Pull request by axot**
Compare to `AMQPSocketConnection` `AMQPStreamConnection` get much slower response on first connection.

https://github.com/php-amqplib/php-amqplib/issues/516
https://github.com/php-amqplib/php-amqplib/issues/449

### CODE REVIEW

**Comment by axot** [comment]
Is it possible backport this to all versions?

**Comment by vyuldashev** [comment]
We need to give developer an option to use `AMQPStreamConnection` or `AMQPSockerConnection`

**Comment by axot** [comment]
I agree your idea, a new option `connection_method_socket` was added ;D

**Comment by vyuldashev** [comment]
I think configuration value should be called something like `connector` and it will be an array with class name and options. 

```php
'connector' => [
    'class' => RabbitMQConnector::class,
    'options' => [],
],
```

Class can be one of `RabbitMQConnectorSocket::class`, `RabbitMQConnectorSSL::class` or `RabbitMQConnector::class` by default.

**Comment by axot** [comment]
Should we move `ssl_params` into new `connector -> options`, what do you think?

**Comment by vyuldashev** [comment]
See #154

**Pull request closed without merging**
