### PR TITLE
feat(PHP) add support php 8.0

### PR DESCRIPTION
**Pull request by Yozhef**

### CODE REVIEW

**Comment by Yozhef** [comment]
Waiting for merge -> https://github.com/php-amqplib/php-amqplib/pull/858 then restart the build and I think everything will be fine.

**Comment by stadeleon** [comment]
It's time to move to PHP-8 
https://github.com/axxapy/php-amqplib/pull/1

**Comment by Yozhef** [comment]
@stadeleon yesterday is OR was merge in the main library - so I think we can wait for the release of the tag.

**Comment by leonidd-hyuna** [comment]
looks like at least one of the bug from PHP8 test were fixed here https://github.com/php-amqplib/php-amqplib/pull/904

**Comment by vyuldashev** [comment]
Let's be patient and wait for stable release of php-amqplib

**Comment by leonidd-hyuna** [comment]
Is it finally released to V3.0.0 ?
https://github.com/php-amqplib/php-amqplib/commit/c0a8eade209b7e43d6a405303d8de716dfd02749

**Comment by vyuldashev** [comment]
I had to make more changes. v11.2.0 with PHP 8 support is released.

**Pull request closed without merging**
