### PR TITLE
change method visibility to allow extension

### PR DESCRIPTION
**Pull request by StevePorter92**
Hey :wave:! I'm currently using this package with Laravel and its working fantastically. I'm in the process of trying to get it to work with Laravel Horizon, and I think I've come pretty close. 

Currently, I'm extending the queue and the job, but because some of the methods and properties are private, i'm having to copy and paste blocks of code to change their visibility.

Can these changes be merged in order to extend the functionality of the Job and the Queue? The Laravel\Horizon\RedisQueue extends the standard Illuminate\Queue\RedisQueue and wraps Horizon Events around queue interactions. Changing the visibility of the methods here would allow us to do the same thing with this RabbitMQ impemntation.

Thanks

### CODE REVIEW

**Comment by vyuldashev** [comment]
Hello. I hope you will share you work afterwards :)

**Comment by StevePorter92** [comment]
@vyuldashev I will! Thanks!

**Comment by StevePorter92** [comment]
Hey @vyuldashev, doesn't look like the latest release 7.1.1 has hit packagist. Would you mind giving it a kick please? 😄

**Comment by vyuldashev** [comment]
Done.

**Comment by vyuldashev** [comment]
@StevePorter92 Cool! Will take a look.

**Comment by vyuldashev** [comment]
@StevePorter92 You can use `^7.1.1` for this library. No breaking changes till 8.0.

**Pull request merged**
