### PR TITLE
[5.1] Allow custom properties when publishing a job

### PR DESCRIPTION
**Pull request by SteffenBach**
RabbitMQ supports additional properties on the message beyond the delivery mode and content type. These properties can be used for sending metadata along the published payload, which can be very useful if the message consumer is written in something other than Laravel.

### CODE REVIEW

**Comment by SteffenBach** [comment]
If I'm understanding you correctly, you want to rename the array key `properties` to something else. 
I'm not against that, but I chose the term _properties_ very deliberately. The reason being, it matches the terminology used by the RabbitMQ Management UI when viewing a message.

I don't see the conflict you are talking about. Would you mind elaborating?

**Comment by vladimir-yuldashev** [comment]
@SteffenBach I mean get properties from incoming ``$options['_rabbitmq_properties']`` and convert to ``$properties['properties']``

**Comment by SteffenBach** [comment]
@vladimir-yuldashev But that introduces an extra level of nesting, which prevents these properties from being really useful. They should be allowed to operate at the root level, so that it's possible for the caller to override what is specified in `$properties`. I.e., if they want to override the content type, or specify one of the other RabbitMQ message properties.

**Comment by vladimir-yuldashev** [comment]
@SteffenBach sorry about forgetting this PR. Is this still required?

**Comment by beerkeeper** [comment]
+1 for this feature.
I'm looking for a way to give messages priority over the other, and with this solution I can do that.

**Pull request closed without merging**
