### PR TITLE
fix #418 - custom exchange

### LINKED ISSUE #418: Custom exchange in pushRaw options
- Laravel/Lumen version: 6
- RabbitMQ version: 3.7
- Package version: 10.2.3

**Describe the bug**

Can't specify custom exchange in pushRaw function options parameters

**Steps To Reproduce**

```
 Queue::pushRaw($payload, null, [
            'exchange' => $event->exchange,
            'exchange_routing_key' => $event->exchange_routing_key
        ]);
```

**Current behavior**

the message not reaching the specified exchange (custom exchange other that the one in config file)

**Expected behavior**

Submit message to specified exchange

**Additional context**

this is a proposition to allow pushing to custom exchanges 

```
protected function publishProperties($queue, array $options = []): array
    {
        $queue = $this->getQueue($queue);
        $attempts = Arr::get($options, 'attempts') ?: 0;
        $exchange = Arr::get($options, 'exchange') ?: null;
        $exchangeRoutingKey = Arr::get($options, 'exchange_routing_key') ?: $queue;
        $destination = $this->getRoutingKey($exchangeRoutingKey);
        $exchange = $this->getExchange($exchange);
        $exchangeType = $this->getExchangeType();

        return [$destination, $exchange, $exchangeType, $attempts];
    }
```

### PR DESCRIPTION
**Pull request by spider4216**
**Current behavior**
the message not reaching the specified exchange and routing key because choose configuration values

**Expected behavior**
Submit message to specified exchange and routing key

**Pull request**
This Pull Request fix this issue via new options parameter in `push` and `pushRaw` methods

### CODE REVIEW

**Comment by spider4216** [comment]
Merging this request can help close #418 issue

Note: this fix tested in v11.2 version. Need creating new minor version: v11.4

**Comment by khepin** [comment]
I don't think code changes are necessary here. The exchange is meant to be set where you define the connections in your configuration files.
You could then refer to the connection you want in code as follows: `Queue::connection('conn_for_exchange_1'); Queue::connection('conn_for_exchange_2');`

The `Queueable` trait in Laravel will also let you specify which queue + connection your job should be sent to:

```
class MyQueuedJob
{
    use Queueable;

    public $connection = 'connection_for_exchange_6';

    public $queue = 'routing.#.key.*';
}
```

Closing this issue as this seems to be fully covered by the library already.

**Comment by spider4216** [comment]
> The exchange is meant to be set where you define the connections in your configuration files.

Hi @khepin, thank you for your feedback! Do you mean if I need to use multiply exchanges and routing keys in my app I need to specify multiply connections?

**Comment by khepin** [comment]
Exchanges yes. But `queue` and `routing_key` are interchangeable when using this library with rabbitmq so you don't need to create 1 connection for each routing key you intend to use.

**Comment by spider4216** [comment]
@khepin, don't you think it's a little bit uncomfortable? For instance in my app I have multiply exchanges with the same connection and I have to specify a lot of connections for each exchange to use them.

I see that a lot of people faced with that problem. For instance [here](https://stackoverflow.com/questions/53859327/how-to-configure-multiple-exchanges-in-laravel-queue-rabbitmq) and [here](https://github.com/vyuldashev/laravel-queue-rabbitmq/issues/418). Now I use another tool which give me a chance to use custom exchange in the same connection dynamically, but maybe you consider an option to achieve a goal with multiply exchanges in one connection?

**Pull request closed without merging**
