### PR TITLE
fix #449 #499 #501 

### LINKED ISSUE #449: The delay parameter of horizon is defined, but it is useless
- Laravel/Lumen version: laravel 8.4.3
- RabbitMQ version: 3.9.3
- Package version: 11.3

**Describe the bug**

image
image

The delay parameter is in the options parameter, but it is not used in the method. I think this is a problem. My solution is to modify parent:: pushRaw() to parent:: laterRaw()

image

The problem on my side has been solved, but I don't know whether such modification will have an impact on the source code

### LINKED ISSUE #499: PHP Fatal error:  Declaration of VladimirYuldashev\LaravelQueueRabbitMQ\Consumer::stop($status = 0): int must be compatible with Illuminate\Queue\Worker::stop($status = 0, $options = null)
I used command: 

composer update at laravel version 9.42

log:

`PHP Fatal error:  Declaration of VladimirYuldashev\LaravelQueueRabbitMQ\Consumer::stop($status = 0): int must be compatible with Illuminate\Queue\Worker::stop($status = 0, $options = null) in /home/gabriel/Projekty/subjects_and_grades/vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Consumer.php on line 200

   Symfony\Component\ErrorHandler\Error\FatalError 

  Declaration of VladimirYuldashev\LaravelQueueRabbitMQ\Consumer::stop($status = 0): int must be compatible with Illuminate\Queue\Worker::stop($status = 0, $options = null)

  at vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Consumer.php:200
    196▕      *
    197▕      * @param  int  $status
    198▕      * @return int
    199▕      */
  ➜ 200▕     public function stop($status = 0): int
    201▕     {
    202▕         // Tell the server you are going to stop consuming.
    203▕         // It will finish up the last message and not send you any more.
    204▕         $this->channel->basic_cancel($this->consumerTag, false, true);

   Whoops\Exception\ErrorException 

  Declaration of VladimirYuldashev\LaravelQueueRabbitMQ\Consumer::stop($status = 0): int must be compatible with Illuminate\Queue\Worker::stop($status = 0, $options = null)

  at vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Consumer.php:200
    196▕      *
    197▕      * @param  int  $status
    198▕      * @return int
    199▕      */
  ➜ 200▕     public function stop($status = 0): int
    201▕     {
    202▕         // Tell the server you are going to stop consuming.
    203▕         // It will finish up the last message and not send you any more.
    204▕         $this->channel->basic_cancel($this->consumerTag, false, true);

      +1 vendor frames 
  2   [internal]:0
      Whoops\Run::handleShutdown()
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 255
`

### LINKED ISSUE #501: Use 'horizon' to manage queues and the configuration `delay` property is invalid
- Laravel/Lumen version: 
```shell
# php artisan --version
Laravel Framework 9.41.0
```
- RabbitMQ version: 
```shell
3.10
```
- Package version: 
```shell
# composer show vladimir-yuldashev/laravel-queue-rabbitmq |grep versions
versions : * v13.0.1
```

**Describe the bug**
**Set a property `public $delay = 60;` in the job class,  job not executing but message is being consumed and ack'ed**

The RabbitMQ message is consumed, but the task is not executed, and the status of the message in the Horizon management interface has not changed

> job file content
```php
<?php

namespace App\Jobs\Notification;

use App\Jobs\BaseJob;
use Illuminate\Support\Facades\Log;


/**
 * Class SystemNotification
 */
class SystemNotification extends BaseJob
{
    public $delay = 60;

    protected array $message = [];

    public function __construct(array $message)
    {
        $this->message = $message;    
    }

    public function handle(): void
    {
        Log::debug('test delay job: '.PHP_EOL.json_encode($this->message));
    }
}

```

**Steps To Reproduce**

copy code and run

**Current behavior**

- What happens with the worker?
- Is the message retried or put back into the queue?
The rabbitMQ control panel sees that it has been consumed
- Is the message acknowledged or rejected?
acknowledged
- Is the message unacked?
no
- Is the message gone?
yes, For rabbitMQ, it should be consumed normally

**Expected behavior**

can run normally in Horizon

**Additional context**

Add any other context about the problem or describe the use-case.

#449

### PR DESCRIPTION
**Pull request by shuqingzai**
Closes #449 
Closes #499 
Closes #501

### CODE REVIEW

**Review by s-nunez — APPROVED** [review]

**Comment by oprudkyi** [comment]
Hi @shuqingzai 
Thank you for fix, but you probably have to run 
```
./vendor/bin/pint
```
to fix code style issues as well
img

**Comment by shuqingzai** [comment]
> Hi @shuqingzai Thank you for fix, but you probably have to run
> 
> ```
> ./vendor/bin/pint
> ```
> 
> to fix code style issues as well img

Hello @oprudkyi , I have performed code formatting, looking forward to merge

**Review by JochenPfaeffle — APPROVED** [review]

**Comment by jvanschie** [comment]
It would be nice to have this one merged

**Comment by mdbw3** [comment]
Also waiting for this one!

**Comment by JochenPfaeffle** [comment]
@vyuldashev can you merge this pull request please.

**Comment by M-Porter** [comment]
Hi all, new maintainers (myself being one) were just added.

Going through and getting up to speed to help get this merged in!

**Review by M-Porter — APPROVED** [review]

**Review by khepin — APPROVED** [review]

**Pull request merged**
