### PR TITLE
Added support for SSL connections.

### PR DESCRIPTION
**Pull request by werewolf81**
This allows to use RabbitMQ via SSL. The minimum requirement for this is having a CA file (can be self-signed).

### CODE REVIEW

**Comment by werewolf81** [comment]
Hi Vladimir. 

First of all, thank you for the amazing package, it works brilliant with Laravel.

Second of all, I have made SSL support for the project I'm working on and thought that my changes can be actually added to your package so other people can use them.

To be able to run tests you need to have own CA file. Also RabbitMQ needs to be configured to accept SSL connections which might be on a different port than standard connections.

Please let me know if you need me to change anything.

Thanks!

**Comment by vladimir-yuldashev** [comment]
Hello. Tests are failing on Travis. Can you add necessary configuration to .travis.yml in order them to pass?

**Comment by werewolf81** [comment]
Do you mean that I can set up additional configuration for RabbitMQ (for SSL) directly in the travis.yml file?

**Comment by vladimir-yuldashev** [comment]
Yes.

**Comment by werewolf81** [comment]
I didn't know that! I'll give it a go and update the pull request once it's done.

**Pull request closed without merging**
