### PR TITLE
Laravel 9.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 9.x.

**Before merging**, you need to:

- Checkout the `l9-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:warning: Shift detected GitHub Actions which run jobs using a version `matrix`. Shift attempted to [update your configuration](https://github.com/vyuldashev/laravel-queue-rabbitmq/pull/463/commits/8b6e5ae8b4f544ca1fe59024f9a0daef555479c6?w=1) for Laravel 9. However, you should review these changes to ensure the desired combination of versions are built for your package.

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/laravel-queue-rabbitmq.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "vyuldashev/laravel-queue-rabbitmq": "dev-l9-compatibility",
    }
}
```

Finally, run: `composer update`

**Review by GarryLai — APPROVED** [review]

**Comment by Gildus** [comment]
And what about https://github.com/vyuldashev/laravel-queue-rabbitmq/pull/467 ?

**Comment by kovalovme** [comment]
Please approve @vyuldashev

**Review by FelipeeDev — APPROVED** [review]

**Review by kovalovme — APPROVED** [review]

**Comment by vyuldashev** [comment]
Laravel 9 support has been released

**Comment by ruedigerm-playster** [comment]
> Laravel 9 support has been released

Laravel 9 support is not yet mentioned in table on README

**Pull request closed without merging**
