### PR TITLE
Feature/abbility to hook into the created connection

### PR DESCRIPTION
**Pull request by adm-bome**
@vyuldashev What do you think?
Issue: #384 PR: #385

### CODE REVIEW

**Comment by adm-bome** [comment]
@vyuldashev i hope this feature is implemented.
Why you may ask?
The reasons are:

1. @fredsted is coming with a question about a functionality the library Php-AmqpLib is providing. It's a matter of time someone else asks the same question.
2. Some-one does not have to use this feature when they don't need it. Laravel and all other libraries/packages are filled with unused events.
3. Another thing is that the middleware approach is ok-isch and works on a per job basis, its alot of overhead for every job. When you want to register the PCNTLHeartbeatSender on a connection basis this is the approach everyone should use.
4. This feature is an hook. It does not have to mean, a programmer uses this event for just the PCNTLHeartbeatSender.

This feature makes the lib more flexible, and easier to work with over-all.
>Side note: We don't have to implement this feature right now. we could put it aside and on the road-map for the next release

**Comment by vyuldashev** [comment]
@adm-bome Let's close it until someone will need such functionality. I don't want to add code which is not linked to needs.

**Comment by frops** [comment]
We are need to implement this feature, because our worker not listening after some times. I have read https://blog.mollie.com/keeping-rabbitmq-connections-alive-in-php-b11cb657d5fb and I need to implementation.

Another way - is inheritance  LaravelQueueRabbitMQServiceProvider и RabbitMQConnector, but it's not good way (
Idea with events is very good.
Thank you ;)

**Comment by frops** [comment]
@adm-bome @vyuldashev Can you reopen pull request?

**Comment by jvanschie** [comment]
I also need this feature

**Pull request closed without merging**
